name: Update GitHub Profile Picture

on:
  workflow_dispatch: # Permite execução manual para teste

jobs:
  update-profile-picture:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update GitHub profile picture
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        image="https://torbware.space/images/owner23.jpg"
        echo "Selected image: $image"
        curl -X PATCH -H "Authorization: token $GH_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{\"avatar_url\":\"$image\"}" \
        https://api.github.com/user
